### ISSUE TITLE
Eliminate screen flickering

### ISSUE THREAD

**Issue by rafzby** [rafzby/chip8-emulator#4]

**Comment by giovannygb** [comment]
My statement can be a little weird, but are you sure this isn't the expected behavior?

At first I thought that, since you are using jframe, it was the lack of double buffering or drawing directly into the jframe graphics, but that is not the case, since you are doing both.

Then, just for testing, I started drawing the offScreenImage to files in a temp folder, and the flickering is still there.

After that, i started looking for videos of other emulators and all of them show similar flicker. I am not familiar with the original hardware, but maybe that was some kind of limitation?

I tested it just with the pong rom. I don't know if i am looking at the right thing or if the problem is worse with another game.

**Comment by rafzby** [comment]
Hi, thanks for your response. I think you're right, probably this is how it behave. I'm gonna close this issue.
